"""
replace_anonymized_names.py

Purpose:
- Restore real names in a JSON file after using anonymized names in quizzes.

Input:
- JSON file with Friend_A / Friend_B placeholders
- name_mapping.json (generated by anonymize_facebook.py)

Output:
- JSON file with Friend_X replaced by real names

Usage Notes:
- Works recursively in JSON structure.
- Keeps formatting intact.
- Use for answer keys or revealing correct responses in the quiz.
"""

import json
import re

# ---- CONFIG ----
INPUT_FILE = "quiz.json"
MAPPING_FILE = "name_mapping.json"
OUTPUT_FILE = "quiz_with_real_names.json"
# -----------------

def main():
    # Load the quiz file
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Load mapping: real name -> anonymized
    with open(MAPPING_FILE, "r", encoding="utf-8") as f:
        mapping = json.load(f)

    # Invert mapping: anonymized -> real name
    reverse_map = {v: k for k, v in mapping.items()}

    # Function to replace anonymized names inside a string
    def replace_names(text):
        if not isinstance(text, str):
            return text
        for anon, real in reverse_map.items():
            # Replace full word occurrences only (case-insensitive)
            pattern = re.compile(r'\b' + re.escape(anon) + r'\b', re.IGNORECASE)
            text = pattern.sub(real, text)
        return text

    # Recursively replace names in JSON
    def replace_in_obj(obj):
        if isinstance(obj, dict):
            return {k: replace_in_obj(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [replace_in_obj(v) for v in obj]
        elif isinstance(obj, str):
            return replace_names(obj)
        else:
            return obj

    updated_data = replace_in_obj(data)

    # Save output
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(updated_data, f, indent=2, ensure_ascii=False)

    print(f"Done! Saved quiz with real names to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
